### ISSUE TITLE
swaggerUI  OAuthAdditionalQueryStringParams

### ISSUE THREAD

**Issue by mmtwalid** [vitalybibikov/AzureExtensions.Swashbuckle#105]
Is there a way to configure swaggerUI options like :

c.OAuthClientId(apiSettings.ClientId);
c.OAuthAdditionalQueryStringParams(new Dictionary<string, string>
{
    { "nonce","nonce vlaue" }
});

the goal here is to send the nonce value its required by the Athentification server

**Comment by vitalybibikov** [comment]
Closing this, as not relevant, please reopen if needed
