### ISSUE TITLE
Swagger Ui Custom Css

### ISSUE THREAD

**Issue by SaMirzaei** [vitalybibikov/AzureExtensions.Swashbuckle#106]
Is there a possibility to add a custom CSS to Ui?

**Comment by Cliabhach** [comment]
I don't think there's any good mechanism built into the tool, at least not yet.

It's a little bit of a nuisance, but here's a workaround that should work:
1. load the entire Swagger UI html as a Stream with `ISwashBuckleClient.GetSwaggerUi`
2. read that Stream into a string
3. do string replacement to inject your custom CSS inline

It would look something like this:

```
    Stream ui = client.GetSwaggerUi("swagger.json");

    string theHtml = new StreamReader(ui).ReadToEnd();
    string extra = "<style>mycss</style>";
    // TODO: Inject 'extra' into 'theHtml'

    HttpResponseMessage response = new(HttpStatusCode.OK)
    {
        Content = new StringContent(theHtml, Encoding.UTF8, "text/html")
    };
```

**Comment by vitalybibikov** [comment]
Fixed
