### ISSUE TITLE
Support for .Net 8 Functions

### ISSUE THREAD

**Issue by dkezri** [vitalybibikov/AzureExtensions.Swashbuckle#109]
The Swashbuckle configuration according to the instruction in Read.ME fine is not working in  .Net 8.0 Functions?

**Comment by vitalybibikov** [comment]
Going to be handled soon, work in progress, going to be updated to .NET 8 isolated worker model

**Comment by vitalybibikov** [comment]
Fixed

**Comment by dkezri** [comment]
thank you for replying.
