### ISSUE TITLE
Invalid swagger json generated if QueryStringParameter data type used for String

### ISSUE THREAD

**Issue by ahsunchohan** [vitalybibikov/AzureExtensions.Swashbuckle#15]
If QueryStringParameter is used with data type = string, the generated swagger json is invalid because the type name that is used in the json is the fully-qualified name of system in C#, which is "System.String". The correct value should be "string".

![image](https://user-images.githubusercontent.com/26001761/82685568-b53bc300-9c54-11ea-9ef9-e6c0bdfa0cbd.png)

![image](https://user-images.githubusercontent.com/26001761/82685489-90dfe680-9c54-11ea-88ed-db638300edb9.png)

**Comment by vitalybibikov** [comment]
Hi @ahsunchohan 

Thanks for the contribution, will be fixed in the next ver

**Comment by vitalybibikov** [comment]
I've added 3.2.0-beta version Nuget, that includes the fix.
