### ISSUE TITLE
FileUpload(Question)

### ISSUE THREAD

**Issue by ahsunchohan** [vitalybibikov/AzureExtensions.Swashbuckle#18]
Hi,

Is there any way to allow file or multiple files to be uploaded as part of the body with HTTP Post method?

API works in postman, but the swagger generated doesn't show any file upload button.

**Comment by vitalybibikov** [comment]
Hi @ahsunchohan,

Currently this functionality is missing. I will investigate it.

**Comment by vitalybibikov** [comment]
@ahsunchohan 
Please test "Single file upload" in https://www.nuget.org/packages/AzureExtensions.Swashbuckle/3.2.1-beta

By applying attribute to your action:

`    
[SwaggerUploadFileAttribute("FileName", "File description")]
`
