### ISSUE TITLE
How do i exclude binders from swagger

### ISSUE THREAD

**Issue by amitvig22** [vitalybibikov/AzureExtensions.Swashbuckle#19]
This works great and is excellent to use, how can i exclude the binders from showing up in the swagger doc.

For example I have an API that will store an image via HTTP POST.

The example values are showing the binder schema, i would like it to show just the Image properties instead from the image model.

![image](https://user-images.githubusercontent.com/1823977/83317610-d10a1080-a1e2-11ea-9c00-c20798e422c5.png)

**Comment by vitalybibikov** [comment]
@amitvig22 
Have you tried [SwaggerIgnore] attribute?

**Comment by ahsunchohan** [comment]
I tried [SwaggerIgnore] but it didn't work for me. The only thing that worked for me is to use [Obsolete] attribute.

**Comment by amitvig22** [comment]
Let me try that, thanks. The SwaggerIgnore did not work for me either.

**Comment by vitalybibikov** [comment]
@amitvig22 Can you create repro?

As SwaggerIgnore works perfectly for me

![image](https://user-images.githubusercontent.com/7008739/84130195-9fe3d880-aa4b-11ea-9f08-29348ae3c714.png)


![image](https://user-images.githubusercontent.com/7008739/84130179-98bcca80-aa4b-11ea-99ba-2e1e60b2a6f7.png)

**Comment by amitvig22** [comment]
Please mark this closed. I upgraded to the latest version and it works as you pointed out.
