### ISSUE TITLE
Add extension method to configure for FunctionsStartup

### ISSUE THREAD

**Issue by Tim-Hodge** [vitalybibikov/AzureExtensions.Swashbuckle#20]
Is it possible to have an extension for the v3 FunctionsStartup which works with the new configure method `public override void Configure(IFunctionsHostBuilder builder)` as opposed to the old IWebJobsStartup.

If not, are you aware of how to configure these side-by-side?

**Comment by vitalybibikov** [comment]
@Tim-Hodge Hi Tim,

Yep, it's possible, though it's kinda hacky. 

IFunctionsHostBuilder does not support "AddExtension" method (now)
that allows to Bind Extensions.

So, underneath, I still need to build ServiceProvider and create an instance of IWebJobsBuilder.

`            var wbBuilder = builder.Services.AddWebJobs(x => { return; });`

**Comment by vitalybibikov** [comment]
Also, it's possible to have 2 startup classes:

```
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            // all the DI
        }        
    }   
```

```
    public class WebJobsStartup : IWebJobsStartup
    {
        void IWebJobsStartup.Configure(IWebJobsBuilder builder)
        {
           /// All the extensions
        }
    }
```


Anyway, I've added 3.2.0-beta version Nuget, that supports IFunctionsHostBuilder.
Please, try it.

**Comment by Tim-Hodge** [comment]
Hi @vitalybibikov - can confirm  3.2.0-beta works with IFunctionsHostBuilder, thank you very much!
