### ISSUE TITLE
How to support Oauth2 flow

### ISSUE THREAD

**Issue by tungphuong** [vitalybibikov/AzureExtensions.Swashbuckle#21]
I am trying to add "AddSecurityDefinition" with type "SecuritySchemeType.OAuth2". It can redirect to IDP (Azure B2C) to login. But it fails when callback "http://localhost:7071/oauth2-redirect.html". Could you please let me know how to configure it?

**Comment by vitalybibikov** [comment]
Hi, currently it's not supported, but planned.
I guess I will look into implementing it somewhere in July (after my project release) I guess I should have more time.

**Comment by vitalybibikov** [comment]
Hi, @tungphuong 
First of all I need to see your configuration and what you are trying to achieve.

Better to have a repro of the problem, if possible.


For instance, configuration for oAuth 2.0 Implicit flow might look something like this:


                    x.AddSecurityDefinition("oauth2", new OpenApiSecurityScheme
                    {
                        Description = "JWT Authorization header",
                        Name = "Authorization",
                        In = ParameterLocation.Header,
                        Type = SecuritySchemeType.OAuth2,
                        Scheme = "Bearer",
                        Flows = new OpenApiOAuthFlows()
                        {
                            Implicit = new OpenApiOAuthFlow()
                            {
                                TokenUrl = new Uri($"someurl"),
                                AuthorizationUrl = new Uri($"someurl"),
                                Scopes = { }
                            }
                        }
                    });
                    x.AddSecurityRequirement(new OpenApiSecurityRequirement
                    {
                        {
                            new OpenApiSecurityScheme
                            {
                                Reference = new OpenApiReference
                                {
                                    Type = ReferenceType.SecurityScheme,
                                    Id = "Bearer"
                                }
                            },
                            Array.Empty<string>()
                        }
                    });

**Comment by vitalybibikov** [comment]
Closed as stale

**Comment by tkusnadi** [comment]
Hi, I am facing the same issue as @tungphuong mentioned using @vitalybibikov proposed code snippet from the above.
It error when trying to post back to oauth2-redirect.html:
```
No webpage was found for the web address: http://localhost:7071/oauth2-redirect.html#access_token=xxxxxx
```
My swagger ui's url is: http://localhost:7071/api/Swagger/ui
