### ISSUE TITLE
Question : Are you planning on taking over development of the previous project?

### ISSUE THREAD

**Issue by uprightbass360** [vitalybibikov/AzureExtensions.Swashbuckle#24]
Stumbled on the forked project and was wondering if you were going to be taking over issues on the on it. I am shopping for some swagger tooling for a couple functions.

**Comment by vitalybibikov** [comment]
@uprightbass360 

I'm not responsible for the previous project. And I don't have access to it.
This one is being updated as I'm using it in my solutions (that are on AFv3)
