### ISSUE TITLE
Generate enum as string 

### ISSUE THREAD

**Issue by hydrocortisone** [vitalybibikov/AzureExtensions.Swashbuckle#26]
Hi Vitaly,
I have a problem with generation of enums as strings.
I'm not sure, maybe I'm doing something wrong.
So, I have model and enum:
```csharp
public class RequestModel 
{
   [JsonConverter(typeof(StringEnumConverter))]
   public SampleEnum SampleEnum { get; set; }
}

public enum SampleEnum 
{
   One, 
   Two
}
```
This this is being generated in enum numbers, not in string.
I tried to apply (I've seen the warning also :) ):
```csharp
x.DescribeAllEnumsAsStrings();
```
I tried to apply such attributes to the enum fields:
```csharp
[EnumMember(Value = "One")]
```

And I got no luck.
Could you validate is it bug or I'm doing something wrong?

Would be great if it's in samples also.

Thanks!

**Comment by vitalybibikov** [comment]
Enums are not supported in Azure Functions v3. 
So I don't support them also.

https://github.com/Azure/azure-webjobs-sdk-extensions/issues/523

**Comment by hydrocortisone** [comment]
No no, it's not about HttpTrigger and function's deserializing.
I deserialize models myself because Functions deserializer is buggy and unpredictable.
It's about swagger, which is not converting enums on the swagger-ui form to string representations...

**Comment by hydrocortisone** [comment]
For example, you can use such attribute 
```csharp
[RequestBodyType(typeof(StartJobRequestModel), "Start job request")] HttpRequest req)
```
and deserialize further.
But swagger will show all enums inside this model as ints....

**Comment by vitalybibikov** [comment]
Starting from Swagger 3 it's only possible to configure this via SerializerSettings.
If it is possible to configure them, then you are OK.
But I don't think that it is possible to do so at the moment

**Comment by mligtenberg** [comment]
Try putting
```Csharp
[JsonConverter(typeof(StringEnumConverter))] 
```
Above your enum definition. That is how I managed to get it working

**Comment by vitalybibikov** [comment]
This one uses Newton, AFAIR.

Both using Newton and System.Text is not a great option to my mind.

While analogous property from System.Text does not work at the moment.

**Comment by hydrocortisone** [comment]
> Try putting
> 
> ```cs
> [JsonConverter(typeof(StringEnumConverter))] 
> ```
> 
> Above your enum definition. That is how I managed to get it working

I tried, didn't work.
Will try again tomorrow...

**Comment by hydrocortisone** [comment]
> 
> 
> Try putting
> 
> ```cs
> [JsonConverter(typeof(StringEnumConverter))] 
> ```
> 
> Above your enum definition. That is how I managed to get it working

`[6/10/2020 6:50:52 AM] Executed 'Swagger' (Failed, Id=22ecf669-ea47-4775-a0c6-afbbbbeeed2f)
[6/10/2020 6:50:52 AM] System.Private.CoreLib: Exception while executing function: Swagger. System.Text.Json: The converter specified on 'Dexmach.Automation.Functions.Models.RuntimeStackEnum' does not derive from JsonConverter or have a public parameterless constructor.`
This is what I've got if I put this tag above the definition.

**Comment by mligtenberg** [comment]
That is an odd error, just to be sure your enum definition looks something like this:
``` C#
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace {{NAMESPACE}}
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum {{ENUMNAME}} {
        [EnumMember(Value = "option1")]
        option1 = 1,
        [EnumMember(Value = "option2")]
        option2 = 2
    }
}
```
Note that I only tested this with the System.Text.Json variant. This is copied from a working sample using the 3.1.6 library.

**Comment by hydrocortisone** [comment]
> 
> 
> That is an odd error, just to be sure your enum definition looks something like this:
> 
> ```cs
> using System.Runtime.Serialization;
> using System.Text.Json.Serialization;
> 
> namespace {{NAMESPACE}}
> {
>     [JsonConverter(typeof(JsonStringEnumConverter))]
>     public enum {{ENUMNAME}} {
>         [EnumMember(Value = "option1")]
>         option1 = 1,
>         [EnumMember(Value = "option2")]
>         option2 = 2
>     }
> }
> ```
> 
> Note that I only tested this with the System.Text.Json variant. This is copied from a working sample using the 3.1.6 library.

That works now!
But, 
`[JsonConverter(typeof(StringEnumConverter))] ` is not `[JsonConverter(typeof(JsonStringEnumConverter))]` ;-)
