### ISSUE TITLE
Function params in xml are not rendered in UI

### ISSUE THREAD

**Issue by hydrocortisone** [vitalybibikov/AzureExtensions.Swashbuckle#27]
Hi, I found one problem when you specify param description and it's not rendered on UI.
I tried the same scenario for asp.net core swashbuckle and it works fine.

```csharp
/// <summary>
/// Function 1.
/// </summary>
/// <param name="name">name name.</param>
/// <returns></returns>
[FunctionName("Function1")]
[RequestHttpHeader("Authorization", isRequired: true)]
public static async Task<IActionResult> Run(
    [HttpTrigger(AuthorizationLevel.Function, "get", Route = "v1/job/{name}")] HttpRequest req,
    string name,
    ILogger log)
{
    log.LogInformation("C# HTTP trigger function processed a request.");

    string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
    dynamic data = JsonConvert.DeserializeObject(requestBody);
    name = name ?? data?.name;

    string responseMessage = string.IsNullOrEmpty(name)
        ? "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response."
        : $"Hello, {name}. This HTTP triggered function executed successfully.";

    return new OkObjectResult(responseMessage);
}
```
Functions
![image](https://user-images.githubusercontent.com/28645748/84154609-9cf6e100-aa67-11ea-824a-fdbbc73c78cc.png)

Asp.net core
![image](https://user-images.githubusercontent.com/28645748/84154885-ee06d500-aa67-11ea-8a4a-ac388933eb0b.png)

If you need POCs I can load it for you.

Thanks!

**Comment by neusamir** [comment]
We are facing the same issue. The param description is not outputted in the swagger json. Is there any workaround short of forking the code?

**Comment by hydrocortisone** [comment]
@neusamir I don't have, will live without descriptions for awhile...:D

**Comment by vitalybibikov** [comment]
That's quite interesting. It shows everything except for params

**Comment by vijaymarada** [comment]
++ Me, Looking for an update.

**Comment by vitalybibikov** [comment]
Please, check it in beta => https://www.nuget.org/packages/AzureExtensions.Swashbuckle/3.3.0-beta
