### ISSUE TITLE
Displaying string value of enums.

### ISSUE THREAD

**Issue by homanizer** [vitalybibikov/AzureExtensions.Swashbuckle#32]
I am not able to generete swagger using string value of enums. I have both tried using `[JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]`  and DescribeAllEnumsAsStrings() in SwaggerGenOptions.

No matter it dipsplays int32 value. 

I wish to display YES and NO instead of 0 and 1

**Comment by vitalybibikov** [comment]
As this package (Newton) is obsolete, some functionality has been moved to Swashbuckle.AspNetCore.Newtonsoft package

Have you tried to use AddSwaggerGenNewtonsoftSupport()? 

Please, create a repro if it won't work.

**Comment by stephanruhland** [comment]
In my project the extension method AddSwaggerGenNewtonsoftSupport() doesnt work.
Its a DotNetCore 3.1 function with the newest stable NuGet.

My solution was to implement a custom filter (ISchemaFilter) and overwrite the enum definition.

**Comment by DarinMacRae** [comment]
I am having the same issue.

I've updated to the latest versions of AzureExtensions.Swashbuckle and Swashbuckle.AspNetCore.Newtonsoft 

and added 
```
public class WebJobsStartup : IWebJobsStartup
{
...
            services.AddSwaggerGenNewtonsoftSupport();
...
}
```

I've decorated the enum with [JsonConverter(typeof(StringEnumConverter))] and also on the property itself.

@vitalybibikov Would you mind updating your sample to include an enum property to show us how to make this work correctly without having to write custom filters? That should not be necessary.

**Comment by DarinMacRae** [comment]
I took a different route by removing all refs to Newtonsoft and just using the new System.Text.Json attributes and this works for me now.

**Comment by vitalybibikov** [comment]
I'm not sure whether Newtonsoft support should be added at all, as multiple Serializers will definitely give me an extra amount of work during testins/development.

Moreover, Newtonsoft is already "deprecated" ([link](https://visualstudiomagazine.com/articles/2020/07/28/json-serializers.aspx)) in .NET core 3, and upcoming .NET 5 adds even more benefits to System.Text.Json.

So, at the moment, I'm just going to wait and  see whether this support is actually required by the masses.

**Comment by amitvig22** [comment]
> I took a different route by removing all refs to Newtonsoft and just using the new System.Text.Json attributes and this works for me now.

Can you provide the sample code for what you did ? 
is this what you added ?
services.AddMvcCore().AddJsonOptions(x =>
            {
                x.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
            });

**Comment by DarinMacRae** [comment]
@amitvig22 No, since this was entirely for Azure Functions I didn't need to configure anything related to MVC. I just stopped using the Newtonsoft attributes and used the System.Text.Json ones.

`[System.Text.Json.Serialization.JsonConverter(typeof(JsonStringEnumConverter))]`

**Comment by vitalybibikov** [comment]
So, I guess I'm going to close this one, as Newtonsoft is not the future of .NET Core/.NET 5 and Azure Functions

**Comment by tommck** [comment]
@vitalybibikov I thought that the current Azure Functions libraries explicitly rely on NewtonSoft libraries and do NOT use STJ... Am I wrong?

**Comment by DarinMacRae** [comment]
Azure Functions can definitely be a confusing landscape.

Here is a working example of now to decorate types containing enums in case it helps anyone running into this issue. (NOTE: This also includes other decorators for Newtonsoft serialization.)

Swagger can now generate the docs so that enums are described as strings.

![image](https://user-images.githubusercontent.com/3474753/112657075-42205180-8e0f-11eb-8a9e-5ca6b87e8051.png)


```
using System.Runtime.Serialization;
using System.Text.Json.Serialization;
using Newtonsoft.Json.Converters;

namespace Swagger
{
    [Newtonsoft.Json.JsonConverter(typeof(StringEnumConverter))]
    [JsonConverter(typeof(JsonStringEnumMemberConverter))]
    public enum GeoJSONObjectType
    {
        [EnumMember] Point,
        [EnumMember] MultiPoint,
        [EnumMember] LineString,
        [EnumMember] MultiLineString,
        [EnumMember] Polygon,
        [EnumMember] MultiPolygon,
        [EnumMember] GeometryCollection,
        [EnumMember] Feature,
        [EnumMember] FeatureCollection,
    }
}
------
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Newtonsoft.Json;

namespace Swagger
{
    public class FeatureCollection
    {
        [Required]
        [JsonRequired]
        [JsonProperty(PropertyName = "type", Required = Required.Always, DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("type")]
        public GeoJSONObjectType Type { get; }

        [Required]
        [JsonRequired]
        [JsonProperty(PropertyName = "features", Required = Required.Always)]
        [JsonPropertyName("features")]
        public List<Feature> Features { get; private set; }
    }

    public class Feature
    {
        [Required]
        [JsonRequired]
        [JsonProperty(PropertyName = "type", Required = Required.Always, DefaultValueHandling = DefaultValueHandling.Include)]
        [JsonPropertyName("type")]
        public GeoJSONObjectType Type { get; }

        [JsonProperty(PropertyName = "id", NullValueHandling = NullValueHandling.Ignore)]
        [JsonPropertyName("id")]
        public string Id { get; }

        [JsonProperty(PropertyName = "geometry", Required = Required.AllowNull)]
        [JsonPropertyName("geometry")]
        public IGeometryObject Geometry { get; }

        [JsonProperty(PropertyName = "properties", Required = Required.AllowNull)]
        [JsonPropertyName("properties")]
        public Dictionary<string, object> Properties { get; }
    }

    public interface IGeometryObject
    {
        GeoJSONObjectType Type { get; }
    }
}
```
