### ISSUE TITLE
Issues with * and ? in Route

### ISSUE THREAD

**Issue by TakeitEasyAlan** [vitalybibikov/AzureExtensions.Swashbuckle#33]
Route = "customer/{token}/{id:**int?**}

The swagger UI, will not closes the {id}, so it will display the path without the closing }

/api/v1/agreement/{token}/**{id**

Route = "content/{language:length(2)}/{feature}/{***path**}"

If there is a star in the route string, the the UI will shown path, as type for both language and feature, and no path parameter.

So there seems to be an issue with wildcards and optional parameters.

**Comment by vitalybibikov** [comment]
Optional parameters are not supported, accordingly with the spec.

Can't say anything about wildcard at the moment, will check it out

**Comment by TakeitEasyAlan** [comment]
Thanks :-)

**Comment by vitalybibikov** [comment]
Hi @TakeitEasyAlan 

As far as I can see SwaggerGen and Conventional routing are not compatible. (at least at the moment)

Can you actually extrapolate on in what cases this routing scheme can be used with Azure Functions?

Thanks

**Comment by TakeitEasyAlan** [comment]
Works fine in Azure, i do the following:-)

  public class SwaggerApi
    {
        /// <summary>
        /// Gets the JSON representation of the functions
        /// </summary>
        /// <param name="req"></param>
        /// <param name="swashBuckleClient"></param>
        /// <returns></returns>
        [SwaggerIgnore]
        [FunctionName("Swagger")]
        public static Task<HttpResponseMessage> GetJson(
            [HttpTrigger(AuthorizationLevel.Anonymous, Constants.HttpMethod.Get, Route = "Swagger/json")] HttpRequestMessage req,
            [SwashBuckleClient] ISwashBuckleClient swashBuckleClient)
        {
            return Task.FromResult(swashBuckleClient.CreateSwaggerDocumentResponse(req));
        }

        /// <summary>
        /// Gets the swagger HTML client
        /// </summary>
        /// <param name="req"></param>
        /// <param name="swashBuckleClient"></param>
        /// <returns></returns>
        [SwaggerIgnore]
        [FunctionName("SwaggerUi")]
        public static Task<HttpResponseMessage> GetClientUI(
            [HttpTrigger(AuthorizationLevel.Anonymous, Constants.HttpMethod.Get, Route = "Swagger/ui")] HttpRequestMessage req,
            [SwashBuckleClient] ISwashBuckleClient swashBuckleClient)
        {
            return Task.FromResult(swashBuckleClient.CreateSwaggerUIResponse(req, "swagger/json"));
        }
    }

**Comment by vitalybibikov** [comment]
I finally checked it, sorry for the wait. 
Anyway, wildcards are not supported by the OpenAPI spec as well and I don't think it will be in the nearest future.

https://github.com/OAI/OpenAPI-Specification/issues/892#issuecomment-281449239
https://github.com/OAI/OpenAPI-Specification/issues/291

There is a workaround, which is not exactly the same, but still might help.

https://stackoverflow.com/questions/42335178/swagger-wildcard-path-parameters
