### ISSUE TITLE
How to hide Models(Schemas) below Swagger UI document

### ISSUE THREAD

**Issue by SankarSutapalli** [vitalybibikov/AzureExtensions.Swashbuckle#35]
Using AzureExtensions.Swashbuckle 3.2.2

I have tried with below code but it removing total schemas. 
But my requirement is to hide Models(Schemas) section.

x.DocumentFilter<RemoveSchemasFilter>();

internal class RemoveSchemasFilter : IDocumentFilter
    {
        public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
        {
            OpenApiComponents var = swaggerDoc.Components;
            var.Schemas.Clear();
            swaggerDoc.Components = var;
        }
    }

**Comment by SankarSutapalli** [comment]
Guys any help on this...........

**Comment by vitalybibikov** [comment]
Hi @SankarSutapalli 

Please give me a bit more details in order to understand what you are trying to achieve. 

- What is the goal?
- Any implementation details or working example would be appreciated

**Comment by SankarSutapalli** [comment]
Hi @vitalybibikov 
Thanks for response
i have attached sample doc
we want to hide/remove below "Schema" section
[Swagger_CM_CustomerInfo.pdf](https://github.com/vitalybibikov/AzureExtensions.Swashbuckle/files/5201002/Swagger_CM_CustomerInfo.pdf)

**Comment by vitalybibikov** [comment]
Hi, @SankarSutapalli 

You need to add the following inthe  Startup into ConfigureSwaggerGensection:

`                    x.DocumentFilter<RemoveSchemasFilter>();`

And a filter:

`    public class RemoveSchemasDocumentFilter : IDocumentFilter
    {
        public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
        {
            foreach (KeyValuePair<string, OpenApiSchema> item in swaggerDoc.Components.Schemas)
            {
                swaggerDoc.Components.Schemas.Remove(item.Key);
            }
        }
    }`
