### ISSUE TITLE
camel casing issue

### ISSUE THREAD

**Issue by vijaymarada** [vitalybibikov/AzureExtensions.Swashbuckle#37]
Version: Asp.net core 3.1

All the Models and reposnse models are in camel case( even if all my models are Pascal). Am not sure its issue with this plugin or asp.net core itself.

**Comment by SankarSutapalli** [comment]
Yes, json will use camel notation.

**Comment by vijaymarada** [comment]
@SankarSutapalli it's not the case earlier.. all the responses used to be in Pascal casing..

**Comment by vitalybibikov** [comment]
Hi @vijaymarada,

if you want to customize serialization process, you can create your own SchemaFilter or change serializer.

This is default dotnet core behavior at the moment.

https://gist.github.com/GiorgioG/d674892da20369d2a7869cdc1bf7d41b
