### ISSUE TITLE
Question: Generating JSON Definition File at Build and Release Stage

### ISSUE THREAD

**Issue by aimackenzie** [vitalybibikov/AzureExtensions.Swashbuckle#39]
Do you have a way of generating the json definition file without the function being hosted e.g.

swagger tofile --output [output] [startupassembly] [swaggerdoc]

This would help greatly when doing the build and release pipelines

**Comment by vitalybibikov** [comment]
Hi @aimackenzie 

Functions do not have a proper Entry Point, so it's a bit complicated to pass anything as a param and make them work as a simple CLI application.

You have 2 options here:

1. Reference the func app from another netcoreapp and make all the work there, proxying all the requests.
2. Run them with the help of https://github.com/Azure/azure-functions-core-tools (which I do)
    - func start --build
    - curl to swagger json endpoint.
