### ISSUE TITLE
Unable to retrieve the HTTP headers in code.

### ISSUE THREAD

**Issue by gottacodeemall** [vitalybibikov/AzureExtensions.Swashbuckle#41]
Unable to retrieve the HTTP headers populated on swagger UI in **HttpRequestMessage**.
Populating the headers using the **[RequestHttpHeader("header", isRequired)]** attribute.

**Comment by gottacodeemall** [comment]
AzureExtensions.Swashbuckle: 3.2.2
Azure Functions: 3.0.3
.NET Core: 3.1

**Comment by gottacodeemall** [comment]
[RequestHttpHeader("Authorization", true)]
[RequestHttpHeader("x-ms-root-activity-id", true)]
[RequestHttpHeader("x-ms-session-id", true)]
[RequestHttpHeader("x-ms-tenant-id", true)]
public async Task<Object> MethodName([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "route")] HttpRequestMessage req)

**Comment by vitalybibikov** [comment]
Hi @gottacodeemall 

I can see it works, on latest dev, at least.

![image](https://user-images.githubusercontent.com/7008739/101277715-55a79e00-37c7-11eb-9b55-a2bf63e9528e.png)

![image](https://user-images.githubusercontent.com/7008739/101277726-6b1cc800-37c7-11eb-83e5-ba5b3bd171ab.png)

![image](https://user-images.githubusercontent.com/7008739/101277731-7b34a780-37c7-11eb-9901-928cadb0dec5.png)

I know there was some issue with Azure Functions till August, related to headers. Please, update your functions.
