### ISSUE TITLE
Assembly not signed in nuget package

### ISSUE THREAD

**Issue by OmegaToken** [vitalybibikov/AzureExtensions.Swashbuckle#42]
Could you please sign the assembly so that the assembly has a strong name?

It does not affect functionality but would get rid of some warnings we are getting since wie only develop signed assemblys and get warning messages for every unsigned assembly used.

**Comment by vitalybibikov** [comment]
Strong-naming is not honored in .NET Core and OSS. 
I don't want to break processes of many people with this change, sorry.

if you need to use Strong Names => https://github.com/dsplaisted/strongnamer

It signs all the assemblies at build time
