### ISSUE TITLE
Handling Claims Principals

### ISSUE THREAD

**Issue by chchadha** [vitalybibikov/AzureExtensions.Swashbuckle#45]
Is there support to work with ClaimsPrincipal (both locally and running with Easy Auth)?

Error: 

TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.
--

https://azure.microsoft.com/en-us/blog/simplifying-security-for-serverless-and-web-apps-with-azure-functions-and-app-service/

**Comment by vitalybibikov** [comment]
Currently, this is not supported in functions.
I created an issue to this some time ago =>
https://github.com/Azure/azure-functions-host/issues/4851
