### ISSUE TITLE
Get methods have body

### ISSUE THREAD

**Issue by glres** [vitalybibikov/AzureExtensions.Swashbuckle#46]
All API methods have a body in Swagger UI, including http Get methods. This causes a "TypeError: Window.fetch: HEAD or GET Request cannot have a body" error when methods are executed in the UI. How can I force the library to generate the expected UI?
I'm using AzureExtensions.Swashbuckle version 3.2.2.

**Comment by andrea-spotsoftware** [comment]
> All API methods have a body in Swagger UI, including http Get methods. This causes a "TypeError: Window.fetch: HEAD or GET Request cannot have a body" error when methods are executed in the UI. How can I force the library to generate the expected UI? I'm using AzureExtensions.Swashbuckle version 3.2.2.

How you solved it?
