### ISSUE TITLE
Multiple versions support

### ISSUE THREAD

**Issue by joeyeng** [vitalybibikov/AzureExtensions.Swashbuckle#48]
What are the current options for supporting multiple swagger docs within one function app? How about adding an attribute that associates functions with different swagger docs based on version/name?

For example:

```
[SwaggerDocVersion("v1")]
[FunctionName("MyFunctionV1")]
public void Run(...)
```

```
[SwaggerDocVersion("v2")]
[FunctionName("MyFunctionV2")]
public void Run(...)
```

In Startup.cs:

```
builder.AddSwashBuckle(Assembly.GetExecutingAssembly(), opts =>
            {
                opts.Documents = new[] {
                    new SwaggerDocument { Name = "api-v1", Title = "My API v1", Version = "v1" },
                    new SwaggerDocument { Name = "api-v2", Title = "My API v2", Version = "v2" }
                    }
                };
```

**Comment by vitalybibikov** [comment]
Please, check it in beta => https://www.nuget.org/packages/AzureExtensions.Swashbuckle/3.3.0-beta

**Comment by tommck** [comment]
@vitalybibikov I am using that beta and I can't figure out how to do this.  Is there an example?

**Comment by tommck** [comment]
I cloned the repo and ran the app.. there still seems to be only 1 document.
There are group names on the UI, but there is only one JSON file generated.

Am I missing something?

**Comment by tommck** [comment]
@joeyeng did you ever get this to work?

**Comment by joeyeng** [comment]
@tommck sorry, I haven't tried yet. Perhaps there's a different url you go to for v1 vs v2 doc?

**Comment by tommck** [comment]
@joeyeng I can ask for a specific document name and it still has ALL the functions in it :(

**Comment by joeyeng** [comment]
@vitalybibikov was this ever added to the non-preview version?

**Comment by tommck** [comment]
@joeyeng I actually wrote a blog post about how to do this stuff... trying to see if my company posted it yet

**Comment by tommck** [comment]
It's not published yet (actually 3 posts), but here's the source code for how I configured things to generate multiple docs:

https://github.com/tommck/azure-functions-openapi-blogs/blob/article-three/Startup.cs

If you decorate your functions with this:

```csharp
  [ApiExplorerSettings(GroupName = "Shopping")]
```

it gets picked up in this code.  I'm hoping my whole blog series goes live in the next week or two, so I can also point you to the walkthrough I did then

**Comment by joeyeng** [comment]
This is very slick, thanks @tommck!

**Comment by tommck** [comment]
@joeyeng here is the full 3-part series: 
- Part One: https://www.ais.com/self-documenting-azure-functions-with-c-and-openapi-part-one/
- Part Two: https://www.ais.com/creating-self-documenting-azure-functions-with-c-and-openapi-part-two/
- Part Three: https://www.ais.com/creating-self-documenting-azure-functions-with-c-and-openapi-part-three/
