### ISSUE TITLE
No overloaded method for builder.AddSwashBuckle

### ISSUE THREAD

**Issue by christopherkish** [vitalybibikov/AzureExtensions.Swashbuckle#49]

**Comment by christopherkish** [comment]
builder.AddSwashBuckle(Assembly.GetExecutingAssembly()); does not work in the new 3.2 version. SwaggerDocOptions is required argument. Please update the Getting Started secion on the Code page and explain how and why the doc options are required.

**Comment by christopherkish** [comment]
Also, error message is:

'SwashBuckleStartupExtension.AddSwashBuckle(IWebJobsBuilder, Assembly, Action<SwaggerDocOptions>)' is obsolete: 'Please, use FunctionsStartup instead'

What does that mean exactly?

**Comment by vitalybibikov** [comment]
You can either silence the error or use FunctionStartup Instead.

https://stackoverflow.com/questions/10608309/disabling-obsolete-error-in-c-sharp
