### ISSUE TITLE
ConfigureSwaggerGen

### ISSUE THREAD

**Issue by fmichellonet** [vitalybibikov/AzureExtensions.Swashbuckle#5]
Hello Vitaly,

i was trying to configure swagger like this.

```
builder.AddSwashBuckle(Assembly.GetExecutingAssembly());
            builder.Services.ConfigureSwaggerGen(options =>
            {
                options.CustomOperationIds(apiDesc =>
                {
                    return apiDesc.TryGetMethodInfo(out MethodInfo methodInfo) ? methodInfo.Name : null;
                });
            });

```
but it does not seem to have any effect.
I've also tried to enable Annotation, but it also does not work.

Any ideas?

**Comment by vitalybibikov** [comment]
Hi, fmichellonet 

I have included the fix into 3.1.1-beta package. Please, check it out.

Currently it is in pre-release, as there were several major changes to API/etc.

List of all the changes: https://github.com/vitalybibikov/azure-functions-extensions-swashbuckle/tree/dev

**Comment by fmichellonet** [comment]
Thanks for your help.
I'll give it a try tomorrow.

**Comment by fmichellonet** [comment]
Hello Vitaly, 

great improvement! I've even been able to use Swashbuckle.AspNetCore.Annotations like this : 

```
builder.AddSwashBuckle(Assembly.GetExecutingAssembly(),
                conf =>
                {
                    conf.ConfigureSwaggerGen = options =>
                    {
                        options.EnableAnnotations();
                    };
                });
```

The good news is that SwaggerOperation and SwaggerResponse attributes are working like a charm. I was hoping that SwaggerRequestBody attribute to describe my typed body parameter would do the job. Sadly it doesn't work.
So, i'll keep up with RequestBodyType attribute and HttpRequestMessage, that's a good start!
