### ISSUE TITLE
Security issues on the dependency packages for system.net.http.4.3.0.nupkg and microsoft.aspnetcore.http.2.1.0.nupkg

### ISSUE THREAD

**Issue by BKB503** [vitalybibikov/AzureExtensions.Swashbuckle#51]
Hello Team, 

we are using Swashbuckle thanks for this. when we run the security scan we are identified two packages as high severity vulnerabilities system.net.http.4.3.0 and  microsoft.aspnetcore.http.2.1.0
1) system.net.http.4.3.0  resolution is to upgrade Upgrade to version System.Net.Http - 4.3.4;Microsoft.PowerShell.Commands.Utility - 6.1.0-rc.1 from white source bolt 
2)  microsoft.aspnetcore.http.2.1.0 resolution is to Upgrade to version microsoft.aspnetcore.app - 2.1.21,microsoft.aspnetcore.all - 2.1.21,microsoft.netcore.app - 2.1.21, Microsoft.AspNetCore.Http - 2.1.22

Please share your thoughts on upgrading this packages

**Comment by vitalybibikov** [comment]
Hi @BKB503 

I can't help here, as these assemblies are a part of Microsoft.Azure.WebJobs.Extensions.Http.
For some reason, there is no update to this package.
