### ISSUE TITLE
Is there a way to specify default values in example models?

### ISSUE THREAD

**Issue by hydrocortisone** [vitalybibikov/AzureExtensions.Swashbuckle#52]
Hey, I'd like to know is there a way to specify default swagger ui values in example models?

For example:

![image](https://user-images.githubusercontent.com/28645748/101155424-67ead600-3627-11eb-8cf3-5c48692ed68e.png)

instead of
```json
{
  "status": "string",
  "statusDetails": "string",
  "exception": "string",
  "id": "string"
}
```
I want to have 

```json
{
  "status": "in progress",
  "statusDetails": "",
  "exception": "",
  "id": "12324"
}
```

Thank you!

**Comment by vitalybibikov** [comment]
Hi, @hydrocortisone 
I guess, this is a good enhancement, I will add it in the next version.
