### ISSUE TITLE
Authorization RequestHttpHeader Not Sent

### ISSUE THREAD

**Issue by smadhukar2000** [vitalybibikov/AzureExtensions.Swashbuckle#53]
Hi Vitaly, first of all thanks for providing the nuget package.

I am trying to add Authorization RequestHttpHeader to Azure Function, but this header is not sent with Swagger test call.
Other customer header like "x-functions-key" etc. are being sent with the request.

e.g.
 [FunctionName("GetProducts")]
[RequestHttpHeader("Authorization", true)]
public static IActionResult GetProducts(
            [HttpTrigger(AuthorizationLevel.Function, "get",  Route = "products")] HttpRequest req,
            ILogger log)
{
return products;
}

any idea why this header is stripped?

Thanks in Advance,
Subhash

**Comment by TiagoCastilhos** [comment]
This attribute is used to specify on swagger document that this header is required, not that it will be sent on a request when you test it through the swagger UI.

**Comment by smadhukar2000** [comment]
Thanks Tiago, i think swagger use javascript to send request, as all request headers are sent except Authorization,
So i suspect maybe swagger "swagger-ui-standalone-preset.js" javascript is removing this header?
As this JS is minified code, couldn't run my head through.

Thoughts ?

Thanks in advance

**Comment by smadhukar2000** [comment]
thanks please close the question, issue seems with browser.
