### ISSUE TITLE
Get a consumes to work

### ISSUE THREAD

**Issue by marcelhi** [vitalybibikov/AzureExtensions.Swashbuckle#54]
Hello Vitaly,

First of all, thanks for maintaining this package, very promising.

I am trying to set the "consumes" but am not succeeding.
I want to achieve the following result (in OpenAPI 2.0):

`"consumes": ["application/octet-stream"]`

To achieve this, before I used to use the ConsumesAttribute. 
This used to work fine with AzureFunctions.Extensions.Swashbuckle package from yuka1984 at the time.
Unfortunately, this does not work with your package now.
I have tested in your testcontroller but also there not working:

```
		[Consumes(MediaTypeNames.Application.Octet)]
        [ProducesResponseType(typeof(TestModel[]), (int)HttpStatusCode.OK)]
        [FunctionName("TestGets")]
        [QueryStringParameter("expand", "it is expand parameter", DataType = typeof(int), Required = true)]
        public async Task<IActionResult> Gets([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "test")]
            HttpRequest request)
        {
            return new OkObjectResult(new[] { new TestModel(), new TestModel() });
        }
```
		
I also exchanged it to the Attribute mentioned in the package, 

`[SupportedRequestFormat(MediaTypeNames.Application.Octet)]`

but again no luck until now.. Any suggestions what I can use?

**Comment by vitalybibikov** [comment]
Closing this, as not relevant, please reopen if needed
