### ISSUE TITLE
AddCodeParameter defaults to true

### ISSUE THREAD

**Issue by tommck** [vitalybibikov/AzureExtensions.Swashbuckle#55]
I have no idea what the purpose to adding a random Query String parameter called "code" is, but I really don't think it should default to true (maybe it shouldn't exist at all?)

Can we at least default this to true if we're not going to remove it?

**Comment by stoyles** [comment]
It's the Azure Function Key (API Key) - if your using anonymous authentication then no key is needed otherwise you'll need to provide the key (or add the x-functions-key header).

**Comment by tommck** [comment]
Sorry for my ignorance, but the parameter is always called "code" as a query string parameter?

**Comment by stoyles** [comment]
Yes, if you choose to have an authLevel set to "function" or "admin" on your HTTPTrigger you must provide this API key. You can see this in Azure Portal for the Azure Function, if you navigate to the function and choose the "Get Function URL". 

These are the App Keys that you can generate for your Function App in the Azure Portal.

It's doesn't have to be provided as a query parameter, you could also provide this value by header using the header name of 'x-functions-key'. The Function will find it in either location.

[Azure Functions HTTP trigger - api-key-authorization](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=csharp#api-key-authorization)

When using swagger you would need to supply this parameter if you have authLevel set to anything other then anonymous or the request will fail. Note you don't need this API key when running locally (development environment).

**Comment by tommck** [comment]
@stoyles thanks for the info. That's very helpful
