### ISSUE TITLE
Support for multiple request/response types (oneof, allof, anyof, ...)

### ISSUE THREAD

**Issue by AccsoSG** [vitalybibikov/AzureExtensions.Swashbuckle#57]
It is possible to define multiple request/response types as defined here: https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/ ?

For example, the swagger spec should look like this:
````yaml
paths:
  /pets:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
      responses:
        '200':
          description: Updated
components:
  schemas:
    Dog:
      type: object
      properties:
        bark:
          type: boolean
        breed:
          type: string
          enum: [Dingo, Husky, Retriever, Shepherd]
    Cat:
      type: object
      properties:
        hunts:
          type: boolean
        age:
          type: integer
````

**Comment by vitalybibikov** [comment]
Hi @AccsoSG 

It is supported at the moment

You can use 

UseAllOfForInheritance
UseOneOfForPolymorphism

to achieve the behaviour.

                opts.ConfigureSwaggerGen = x =>
                {
                    x.UseAllOfForInheritance();
                  //
                 //
                //
                }


![image](https://user-images.githubusercontent.com/7008739/112325300-9c60cb80-8cc4-11eb-81bb-970843cc0077.png)
