### ISSUE TITLE
support for Autofac and other IoC container

### ISSUE THREAD

**Issue by joswa888** [vitalybibikov/AzureExtensions.Swashbuckle#62]
Hi, I'm having issues on registering SwashBuckleClient using Autofac, can you expose or make a public constructor of the class? As it's currently internal. Thank you!

![image](https://user-images.githubusercontent.com/8201076/105509946-0b439780-5d09-11eb-8fd6-8a5bdcde09b4.png)

**Comment by vitalybibikov** [comment]
Hi @joswa888 

If that's all that is required I will add it in the next verison

**Comment by vitalybibikov** [comment]
Released in 3.3.2
