### ISSUE TITLE
Can I overwrite function name for the swagger ui? 

### ISSUE THREAD

**Issue by goncrip** [vitalybibikov/AzureExtensions.Swashbuckle#65]
Hi.
I have a question about if I can overwrite the function name to add '/' separator. By default the extension take the function name as the title.

I tried to change the code but it won't allow me that function name with '/'. I want the function route as the title.

![image](https://user-images.githubusercontent.com/19353329/107664158-e2a92080-6c6a-11eb-814a-8855139b2332.png)

**Comment by beastlyDartfordian** [comment]
Not sure how "correct" this is but you can put '[ApiExplorerSettings(GroupName = "exampleName")]' on the method to rename it.

**Comment by vitalybibikov** [comment]
Closing this, as not relevant, please reopen if needed
