### ISSUE TITLE
Can the swagger ui output utilize the web api constraints?

### ISSUE THREAD

**Issue by dellch** [vitalybibikov/AzureExtensions.Swashbuckle#68]
The route configuration option for an HTTP triggered function accepts the following [route constraints](url).  

These don't seem to be fully supported in the swagger UI, or maybe I'm doing something wrong?  

I'm attempting to use  the regular expression route constraint, for example:
```
...
[HttpTrigger(
                AuthorizationLevel.Function,
                "get",
                Route =
                    "api/test/{version:regex(^\\d+\\.\\d+)}")]
            HttpRequest request,
...
```
Wondering if the Swagger UI can support examples?  Let me know if you need more information.

**Comment by vitalybibikov** [comment]
Closing this, as not relevant, please reopen if needed
