### ISSUE TITLE
querystring parameter example update #69

### ISSUE THREAD

**Issue by YARG** [vitalybibikov/AzureExtensions.Swashbuckle#71]
Great work Vitaly on this component, it's been a real help!

What are your plans with respects to new releases, any planned in the next couple of weeks as I could do with this feature:
https://github.com/vitalybibikov/AzureExtensions.Swashbuckle/pull/69

I know I can do a build myself but I'd like to use official released builds, if possible.

Regards

Steve

**Comment by vitalybibikov** [comment]
Sorry for the wait, I released it just now => https://www.nuget.org/packages/AzureExtensions.Swashbuckle/3.3.2

**Comment by vitalybibikov** [comment]
@YARG I'm closing it now, please open a new one if any questions arise

**Comment by YARG** [comment]
Thanks for this, great news!
