### ISSUE TITLE
.NET 5+ support?

### ISSUE THREAD

**Issue by ryanhubbell** [vitalybibikov/AzureExtensions.Swashbuckle#78]
We're using .NET 5 in our Azure Functions, and would love to use this library, however, it seems it's not compatible with the .NET 5 specific Azure Functions SDK.

Error: `AZFW0001: The attribute 'SwashBuckleClientAttribute' is a WebJobs attribute and not supported in the .NET Worker (Isolated Process).`

**Comment by h3x4d3c1m4l** [comment]
This might be helpful for you: https://github.com/hajekj/azure-functions-openapi-demo

Took me a while to find...

**Comment by johnnyreilly** [comment]
Has anyone tested this out with .NET 6 at all?  We're hoping to make the move sometime soon - but given this issue is here I was wondering if we could expect to encounter issues?

**Comment by prashantagrawalcrowe** [comment]
is there any update on this?

**Comment by vitalybibikov** [comment]
Fixed
