### ISSUE TITLE
Dynamic OAuth2RedirectPath

### ISSUE THREAD

**Issue by KondzioSSJ4** [vitalybibikov/AzureExtensions.Swashbuckle#87]
Hi

At this moment OAuth2RedirectPath is allowed to configured static string without knowing about the request context

Some people use some architecture that prevents knowing the endpoint URL for users
and I would like to set OAuth2RedirectPath depends on incoming requests (mostly depends on the host URL part)

Is it possible to allow provide OAuth2RedirectPath depends on the current scope?

**Comment by vitalybibikov** [comment]
Closing this, as not relevant, please reopen if needed
