### ISSUE TITLE
Release notes out of date?

### ISSUE THREAD

**Issue by tommck** [vitalybibikov/AzureExtensions.Swashbuckle#88]
It's a little disconcerting seeing that the latest stable NuGet package is version 3.3.2, but the documentation in the Readme has just 3.3.1-beta listed as its most recent information.

How are we supposed to know what changed?

**Comment by tommck** [comment]
@vitalybibikov can you comment on this? It's been 2 months and we're still in the same situation. This makes me worried about using this at all at this point

**Comment by vitalybibikov** [comment]
Closing this, as not relevant, please reopen if needed
