### ISSUE TITLE
Automatically detect possible responses

### ISSUE THREAD

**Issue by DerStimmler** [vitalybibikov/AzureExtensions.Swashbuckle#92]
Hello, currently it seems that this package is only able to auto-detect my models/DTOs and the different endpoints. But the relation between endpoints and models and the possible response codes have to be manually set by attributes on the several functions.

With Swashbuckle and the SwaggerGen on ASP .NET Core all these things got detected automatically.

Am I missing something or doesn't this package support all features from the official Swashbuckle?

**Comment by vitalybibikov** [comment]
Closing this, as not relevant, please reopen if needed
