### ISSUE TITLE
With .NET 6 Azure Functions getting "Exception of type 'System.OutOfMemoryException' was thrown"

### ISSUE THREAD

**Issue by joeliir** [vitalybibikov/AzureExtensions.Swashbuckle#94]
With .NET 6 Azure Functions and using AzureExtensions.Swashbuckle version 3.3.2. going to https://site/api/Swagger/ui in Azure is throwing a Exception of type 'System.OutOfMemoryException' was thrown error. The json file shows up fine as it just seems to be when loading the UI. This is happening with new APIs that are not being used other than by me. It does work fine when loading it locally.

**Comment by vitalybibikov** [comment]
Going to be fixed in v4.0.0
