### ISSUE TITLE
Question: dotnet 6 and azure functions v4

### ISSUE THREAD

**Issue by svenna** [vitalybibikov/AzureExtensions.Swashbuckle#95]
Hi,

am i correct that this extension doesn't as of now support azure functions v4 (and perhaps dotnet 6)
We use the microsoft.azure.functions.worker.extenstions.openapi but it seems to have a very slow speed and
seem to support few items that are needed to really document an api.

**Comment by joeliir** [comment]
I have it working in .NET 6 with Azure Functions v4 except the UI part. No matter what the UI always gives me a out of memory exception. But the json generates fine.

**Comment by radhewro** [comment]
It works, see my _csproj_:

    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>

**Comment by KondzioSSJ4** [comment]
That would be nice if there will come a new version e.g. 4.x.x
that would support the new version of Azure Functions (v4) with NET 6

That would include also updating all dependent packages
(e.g. newest `Swashbuckle.AspNetCore.*` (6+) throw exception error that some method does not exist)

**Comment by gnalder-hw** [comment]
I'm also trying to use version 3.3.2 with a v4 Azure Function and .NET 6.
`swashBuckleClient.CreateSwaggerJsonDocumentResponse(req)` throws an exception of 
`MissingMethodException: Method not found: 'Void Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository..ctor()'.
`

**Comment by johnnyreilly** [comment]
It looks like this is an abandoned project unfortunately.

For whatever reason @vitalybibikov isn't maintaining this. No judgement on him, doing open source is a gift to the community and not an obligation.

It might be worth some folk forking the project if they'd like to keep using it. If not, then it's probably worth taking a look for alternatives.

**Comment by venkat-vangal** [comment]
When can we expect the release for the upgrade to .Net 6.0

**Comment by johnnyreilly** [comment]
From @vitalybibikov

> @johnnyreilly Sorry, just migrated from Belarus to Ukraine, and after that I had to leave Ukraine to Poland, so for now I'm pretty much limited in time on OSS.

It's probably fair to say that it may be difficult for him to arrange this. If he empowers others then maybe this can be happen

**Comment by kasuken** [comment]
It's very weird.
On my laptop (same project) I see the Swagger UI updated with the custom information I setup in startup file.
On another machine, it works but still see the default Swagger UI interface.

`
    <PackageReference Include="AzureExtensions.Swashbuckle" Version="3.3.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="1.5.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.3" />
`

**Comment by prashantagrawalcrowe** [comment]
Do we have SwashBuckle for isolated azure function?

**Comment by vitalybibikov** [comment]
Going to be fixed in v4.0.0
