### ISSUE TITLE
multipart/form-data

### ISSUE THREAD

**Issue by imrandyk** [vitalybibikov/AzureExtensions.Swashbuckle#96]
If there is a way to support multipart/form-data I'm not seeing? If it is supported how would you accomplish this? If not is there a plan or path to do this?

There is a need to send files as part of the form also.

**Comment by Guilherme-Foppa** [comment]
I try to configure to multipart/form-data but I don't, Is there way to configure ?

**Comment by angelolsantos** [comment]
Any news about this problem?

**Comment by vitalybibikov** [comment]
This is an example of working with multipart data when uploading file, if it's not suffice and issue is still relevant please reopen and add new description. Thanks


![image](https://github.com/vitalybibikov/AzureExtensions.Swashbuckle/assets/7008739/f2996d36-5625-4edf-b0d7-f7c41b236e0e)

For binary file upload

```
        [ProducesResponseType(typeof(TestModel), (int)HttpStatusCode.Created)]
        [RequestHttpHeader("x-ms-session-id", true)]
        [Function("TestUpload")]
        [SwaggerUploadFile("Pdf", "Pdf upload")]
        public async Task<IActionResult> TestUpload(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "test/upload")] HttpRequest req)
        {
            var data = await req.ReadFormAsync();

            if (data != null)
            {
                foreach (var formFile in data.Files)
                {
                    using var reader = new StreamReader(formFile.OpenReadStream());
                    var fileContent = await reader.ReadToEndAsync();
                    return new OkObjectResult(fileContent.Length);
                }
            }

            return new NoContentResult();
        }

```
